name: ToDo API App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine Version
      id: version
      run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

    - name: Restore NuGet Packages
      run: dotnet restore src/

    - name: Build and Publish
      run: dotnet publish src/ -c Release -o ./src/publish

    - name: SonarQube Analysis
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build Docker Image
      run: |
        docker buildx build --tag andrejpopovski123/todoapitest:${{ steps.version.outputs.version }} --file Dockerfile --load ./

    - name: Push Docker Image
      run: |
        docker push andrejpopovski123/todoapitest:${{ steps.version.outputs.version }}
# STEP 3 of TASK
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: latest
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
    - name: Try the cluster!
      run: kubectl get pods -A

