name: Build Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger only on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine Version
      id: version
      run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

    - name: Restore NuGet Packages
      run: dotnet restore src/

    - name: Build and Publish
      run: dotnet publish src/ -c Release -o ./src/publish

    - name: SonarQube Analysis
      uses: SonarSource/sonarcloud-github-action@v1
      with:
        project: "todoapi"
        token: sqa_d2d105f488e23f5b46e8aed1d98e5646a98297e6

    - name: Build Docker Image
      run: |
        docker buildx build --tag andrejpopovski123/todoapitest:${{ steps.version.outputs.version }} --file Dockerfile --load ./

    - name: Push Docker Image
      run: |
        docker push andrejpopovski123/todoapitest:${{ steps.version.outputs.version }}
